version: '3.3'
services:
  lanproxy-client:
    image: franklin5/lanproxy-server
    container_name: lanproxy-server
    environment:
     # 配置后台管理账号，默认admin
     - LANPROXY_USERNAME=admin
     # 配置后台管理密码，默认admin
     - LANPROXY_PASSWORD=cc..1234

    volumes:
     # 用于保存创建的配置文件，避免重启服务后配置消失
     - ./config:/root/.lanproxy
    
    networks:
     mynetwork:
      ipv4_address: "172.18.0.10"
    
    deploy:
      resources:
        limits:
          #cpus: '0.5'
          memory: 512M

    ports:
     - 8090:8090
     - 4900:4900
     - 4993:4993
    restart: always

networks:
  default:
    external:
      name: mynetwork
  mynetwork:
    external: true
