# HTTP 端口
port: 7890

# SOCKS5 端口
socks-port: 7891

# Linux 及 macOS 的 redir 端口
# redir-port: 7892

allow-lan: true

# 仅适用于设置 allow-lan 为 true 时
# "*": 绑定所有 IP 地址
# 192.168.122.11: 绑定单个 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个 IPv6 地址
# bind-address: "*"

# Rule / Global / Direct (默认为 Rule 模式)
mode: Rule

# 设置输出日志的等级 (默认为 info)
# info / warning / error / debug / silent
log-level: silent

# RESTful API for clash
external-controller: :9090

dns:
  enable: true
  ipv6: false
  nameserver:
    - 114.114.114.114
    - 114.114.115.115
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query

proxies:

- {
   name: "🇰🇷 KoreaN (Vmess)",
   type: vmess,
   server: ccnxray.aimdd.com,
   port: 443,
   uuid: 4e79da35-a842-4571-9300-89003db65a68,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /KoreaChuncheonVN,
   ws-headers: {Host: ccnxray.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇰🇷 KoreaN (Trojan)",
   type: trojan,
   server: ccnxray.aimdd.com,
   port: 443,
   password: cc..1234,
   sni: ccnxray.aimdd.com, 
   skip-cert-verify: false
  }

- {
   name: "🇯🇵 JapanN (Vmess)",
   type: vmess,
   server: dbnxray.aimdd.com,
   port: 443,
   uuid: e7632537-11cc-4100-bf42-6de88fffb19f,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /JapanOsakaVN,
   # ws-headers: {Host: dbncfcm.aimdd.com}false
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇯🇵 JapanN CM (Vmess)",
   type: vmess,
   server: dbncfcm.aimdd.com,
   port: 443,
   uuid: e7632537-11cc-4100-bf42-6de88fffb19f,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /JapanOsakaVN,
   # ws-headers: {Host: dbncfcm.aimdd.com}false
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇯🇵 JapanN CU (Vmess)",
   type: vmess,
   server: dbncfcu.aimdd.com,
   port: 443,
   uuid: e7632537-11cc-4100-bf42-6de88fffb19f,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /JapanOsakaVN,
   # ws-headers: {Host: dbncfcu.aimdd.com}
   # udp: true
   # skip-cert-verify: true
  }

- {
   name: "🇯🇵 JapanN (Trojan)",
   type: trojan,
   server: dbnxray.aimdd.com,
   port: 443,
   password: cc..1234,
   sni: dbnxray.aimdd.com, 
   skip-cert-verify: false
  }

- {
   name: "🇭🇰 Az -> 🇸🇬 SingaporeNat (Vmess)", 
   type: vmess,
   server: azhk.aimdd.com,
   port: 443,
   uuid: 8cf59a6a-3cb6-4a1a-f95b-56c785df48be,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /WebNatSG,
   ws-headers: {Host: azhk.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇰🇷 Orcc -> 🇸🇬 SingaporeNat (Vmess)",
   type: vmess,
   server: ccnxray.aimdd.com,
   port: 443,
   uuid: 8cf59a6a-3cb6-4a1a-f95b-56c785df48be,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /WebNatSG,
   ws-headers: {Host: ccnxray.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇸🇬 SingaporeNat CM (Vmess)",
   type: vmess,
   server: natsgcfcm.aimdd.com,
   port: 443,
   uuid: 8cf59a6a-3cb6-4a1a-f95b-56c785df48be,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /WebNatSG,
   # ws-headers: {Host: dbncfcm.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇸🇬 SingaporeNat CU (Vmess)",
   type: vmess,
   server: natsgcfcu.aimdd.com,
   port: 443,
   uuid: 8cf59a6a-3cb6-4a1a-f95b-56c785df48be,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /WebNatSG,
   # ws-headers: {Host: dbncfcu.aimdd.com}
   # udp: true
   # skip-cert-verify: true
  }

- {
   name: "🇺🇸 America (Vmess)",
   type: vmess,
   server: lsjprxray.aimdd.com,
   port: 443,
   uuid: 2266af62-bcdb-4fc7-c1e5-05ba7831c2fa,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /AmericaLosAngelesVN,
   # ws-headers: {Host: lsjprcfcm.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇺🇸 America CM (Vmess)",
   type: vmess,
   server: lsjprcfcm.aimdd.com,
   port: 443,
   uuid: 2266af62-bcdb-4fc7-c1e5-05ba7831c2fa,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /AmericaLosAngelesVN,
   # ws-headers: {Host: lsjprcfcm.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇺🇸 America CU (Vmess)",
   type: vmess,
   server: lsjprcfcu.aimdd.com,
   port: 443,
   uuid: 2266af62-bcdb-4fc7-c1e5-05ba7831c2fa,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /AmericaLosAngelesVN,
   # ws-headers: {Host: lsjprcfcu.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇺🇸 America (Trojan)",
   type: trojan,
   server: lsjprxray.aimdd.com,
   port: 443,
   password: cc..1234,
   sni: lsjprxray.aimdd.com, 
   skip-cert-verify: false
  }

- {
   name: "🇺🇸 America CN2 (Vmess)",
   type: vmess,
   server: usvray.salir.cl,
   port: 443,
   uuid: b491aab9-fad7-44d0-a519-1703ccfa2e16,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /America,
   ws-headers: {Host: usvray.salir.cl}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇺🇸 America CN2 (Trojan)",
   type: trojan,
   server: usxray.salir.cl,
   port: 443,
   password: cc..1234,
   sni: usxray.salir.cl, 
   skip-cert-verify: false
  }

- {
   name: "🇭🇰 Az HongKong (Vmess)",
   type: vmess,
   server: azhk.aimdd.com,
   port: 443,
   uuid: bad6518d-607a-41b0-d567-28f6f46655af,
   alterId: 64,
   cipher: auto,
   tls: true,
   network: ws,
   ws-path: /HongKongVN,
   ws-headers: {Host: azhk.aimdd.com}
   # tls: true
   # skip-cert-verify: true
  }

- {
   name: "🇭🇰 Az HongKong (Trojan)",
   type: trojan,
   server: azhk.aimdd.com,
   port: 443,
   password: cc..1234,
   sni: azhk.aimdd.com, 
   skip-cert-verify: false
  }

proxy-groups:
# 代理节点选择
- name: "Kr节点选择"
  type: select
  proxies:
    - "全球选择"
    - "🇰🇷 KoreaN (Vmess)"
    - "🇰🇷 KoreaN (Trojan)"
    - "🇭🇰 Az HongKong (Vmess)"
    - "🇭🇰 Az HongKong (Trojan)"

#代理节点选择
- name: "Jp节点选择"
  type: select
  proxies:
    - "全球选择"
    - "Kr节点选择"
    - "🇯🇵 JapanN (Vmess)"
    - "🇯🇵 JapanN CM (Vmess)"
    - "🇯🇵 JapanN CU (Vmess)"
    - "🇯🇵 JapanN (Trojan)"

- name: "Hk节点选择"
  type: select
  proxies:
    - "全球选择"
    - "Kr节点选择"
    - "Jp节点选择"
    - "🇭🇰 Az HongKong (Vmess)"
    - "🇭🇰 Az HongKong (Trojan)"

#NatSg节点选择
- name: "NatSg节点选择"
  type: select
  proxies:
    - "全球选择"
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "🇭🇰 Az -> 🇸🇬 SingaporeNat (Vmess)"
    - "🇰🇷 Orcc -> 🇸🇬 SingaporeNat (Vmess)"
    - "🇸🇬 SingaporeNat CM (Vmess)"
    - "🇸🇬 SingaporeNat CU (Vmess)"

#代理节点选择
- name: "Us节点选择"
  type: select
  proxies:
    - "全球选择"
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "🇺🇸 America (Vmess)"
    - "🇺🇸 America CM (Vmess)"
    - "🇺🇸 America CU (Vmess)"
    - "🇺🇸 America (Trojan)"
    - "🇺🇸 America CN2 (Vmess)"
    - "🇺🇸 America CN2 (Trojan)"
    
# 代理节点选择
- name: "facebook节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"
    
- name: "twitter节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"

- name: "telegra节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"
    
- name: "potato节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"

- name: "google节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"

- name: "tiktok节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "netflix节点选择" 
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "github节点选择" 
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "hostloc节点选择" 
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "wiki节点选择" 
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "uptodown节点选择"   
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "pixiv节点选择" 
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点" 

- name: "safechat节点选择"
  type: select
  proxies:
    - "Kr节点选择"
    - "Jp节点选择"
    - "Hk节点选择"
    - "NatSg节点选择"
    - "Us节点选择"
    - "全球选择"
    - "全球全局"
    - "全球节点"

# 特殊地址可直连 
- name: "特殊地址可直连"
  type: select
  proxies:
    - "全球直连" 
    - "全球拦截"
    - "全球全局"
    - "全球节点"

# 微软可直连 
- name: "微软可直连"
  type: select
  proxies:
    - "全球直连" 
    - "全球拦截"
    - "全球全局"
    - "全球节点"

# 苹果可直连 
- name: "苹果可直连"
  type: select
  proxies:
    - "全球直连" 
    - "全球拦截"
    - "全球全局"
    - "全球节点"

# 全球全局
- name: "全球全局"
  type: select
  proxies:
    - "全球选择"
    - "全球节点"

# 全球节点
- name: "全球节点"
  type: select
  proxies:   
    - "Kr节点选择"
    - "Jp节点选择"
    - "NatSg节点选择"
    - "Us节点选择"

# 全局选择
- name: "全球选择"
  type: select
  proxies:
    - "全球直连"
    - "全球拦截"

# 全球拦截 
- name: "全球拦截"
  type: select
  proxies:
    - "REJECT"

# 全球直连 
- name: "全球直连"
  type: select
  proxies:
    - "DIRECT"

# 规则选择
- name: "漏网之鱼"
  type: select
  proxies:
    - "故障选择"
    - "全球直连"
    - "全球拦截"
    - "全球全局"

# 故障选择自动选择
- name: "故障选择"
  type: fallback
  proxies:
    - "全球直连"
    - "全球节点" 
  url: 'http://www.gstatic.com/generate_204'
  interval: 120

#规则
rules:
  - DOMAIN-SUFFIX,nter.aimdd.com,Kr节点选择

  - DOMAIN-SUFFIX,translate.google.cn,特殊地址可直连
  - DOMAIN-KEYWORD,amazon,特殊地址可直连
  - DOMAIN-SUFFIX,amazon.com,特殊地址可直连
 
  - DOMAIN-KEYWORD,gvt,全球节点
  - DOMAIN-KEYWORD,porn,全球节点 #p站
  - DOMAIN-KEYWORD,usky,全球节点
  - DOMAIN-KEYWORD,ssrtool,全球节点
  - DOMAIN-SUFFIX,v2ray.com,全球节点
  - DOMAIN-KEYWORD,freenom,全球节点
  
  - DOMAIN-KEYWORD,github,github节点选择

  - DOMAIN-KEYWORD,hostloc,hostloc节点选择 #全球主机

  - DOMAIN-SUFFIX,wikimapia.org,wiki节点选择 #维基
  - DOMAIN-SUFFIX,wikimedia.org,wiki节点选择 #维基
  - DOMAIN-SUFFIX,wikipedia.org,wiki节点选择 #维基百科
  - DOMAIN-SUFFIX,wikiquote.org,wiki节点选择 #维基
  - DOMAIN-SUFFIX,wikiwand.com,wiki节点选择  #维基

  - DOMAIN-KEYWORD,uptodown,uptodown节点选择 #Uptodown
  - DOMAIN-KEYWORD,apkpure,uptodown节点选择 #Apkpure

  - DOMAIN-SUFFIX,youtu.be,google节点选择
  - DOMAIN-KEYWORD,youtube,google节点选择
  - DOMAIN-SUFFIX,youtube.com,google节点选择
  - DOMAIN,youtubei.googleapis.com,google节点选择
  - DOMAIN-KEYWORD,youtube,google节点选择
  - DOMAIN,youtubei.googleapis.com,google节点选择
  - DOMAIN,yt3.ggpht.com,google节点选择
  - DOMAIN-SUFFIX,googlevideo.com,google节点选择
  - DOMAIN-SUFFIX,gvt2.com,google节点选择
  - DOMAIN-SUFFIX,youtu.be,google节点选择
  - DOMAIN-SUFFIX,youtube.com,google节点选择
  - DOMAIN-SUFFIX,ytimg.com,google节点选择
  - PROCESS-NAME,com.google.android.apps.youtube.music,google节点选择
  - PROCESS-NAME,com.google.android.youtube.tvmusicroot,google节点选择
  - PROCESS-NAME,com.vanced.android.apps.youtube.music,google节点选择

  - DOMAIN-SUFFIX,gvt0.com,google节点选择 #Google Play
  - DOMAIN-SUFFIX,gvt1.com,google节点选择 #Google Play
  - DOMAIN-SUFFIX,gvt3.com,google节点选择 #Google Play
  - DOMAIN-KEYWORD,google,google节点选择
  - DOMAIN-SUFFIX,gmail.com,google节点选择 # 谷歌邮箱
  
  - DOMAIN-SUFFIX,safechat.com,safechat节点选择 #safechat
  - DOMAIN-KEYWORD,safechat,safechat节点选择 #safechat
  - DOMAIN-KEYWORD,ads-pixiv.com,safechat节点选择

  - DOMAIN-KEYWORD,pixiv,pixiv节点选择 #p 漫画
  - DOMAIN-KEYWORD,pximg,pixiv节点选择 #p 漫画

  - DOMAIN-SUFFIX,fb.com,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,fb.me,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,fbaddins.com,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,fbcdn.net,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,fbsbx.com,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,fbworkmail.com,facebook节点选择 #脸书
  - DOMAIN-SUFFIX,instagram.com,facebook节点选择 #instagram
  - DOMAIN-SUFFIX,cdninstagram.com,facebook节点选择 #instagram
  - DOMAIN-KEYWORD,instagram,facebook节点选择 #insta
  - DOMAIN-SUFFIX,m.me,facebook节点选择 
  - DOMAIN-SUFFIX,messenger.com,facebook节点选择
  - DOMAIN-SUFFIX,oculus.com,facebook节点选择
  - DOMAIN-SUFFIX,oculuscdn.com,facebook节点选择
  - DOMAIN-SUFFIX,rocksdb.org,facebook节点选择
  - DOMAIN-SUFFIX,whatsapp.com,facebook节点选择
  - DOMAIN-SUFFIX,whatsapp.net,facebook节点选择
  - DOMAIN-KEYWORD,facebook,facebook节点选择 #脸书

  - DOMAIN-SUFFIX,pscp.tv,twitter节点选择 #推特
  - DOMAIN-SUFFIX,periscope.tv,twitter节点选择 #推特
  - DOMAIN-SUFFIX,t.co,twitter节点选择 #推特
  - DOMAIN-SUFFIX,twimg.co,twitter节点选择 #推特
  - DOMAIN-SUFFIX,twimg.com,twitter节点选择 #推特
  - DOMAIN-SUFFIX,twitpic.com,twitter节点选择 #推特
  - DOMAIN-SUFFIX,vine.co,twitter节点选择 #推特
  - DOMAIN-KEYWORD,twitter,twitter节点选择  #推特

  - DOMAIN-KEYWORD,telegram,telegra节点选择 #电报
  - DOMAIN-SUFFIX,t.me,telegra节点选择 #电报
  - DOMAIN-SUFFIX,tdesktop.com,telegra节点选择 #电报
  - DOMAIN-SUFFIX,telegra.ph,telegra节点选择 #电报
  - DOMAIN-SUFFIX,telegram.me,telegra节点选择 #电报
  - DOMAIN-SUFFIX,telegram.org,telegra节点选择 #电报
  - IP-CIDR,91.108.4.0/22,telegra节点选择,no-resolve #电报
  - IP-CIDR,91.108.8.0/22,telegra节点选择,no-resolve #电报
  - IP-CIDR,91.108.12.0/22,telegra节点选择,no-resolve #电报
  - IP-CIDR,91.108.16.0/22,telegra节点选择,no-resolve #电报
  - IP-CIDR,91.108.56.0/22,telegra节点选择,no-resolve #电报
  - IP-CIDR,149.154.160.0/20,telegra节点选择,no-resolve #电报
  - IP-CIDR6,2001:b28:f23d::/48,telegra节点选择,no-resolve #电报
  - IP-CIDR6,2001:b28:f23f::/48,telegra节点选择,no-resolve #电报
  - IP-CIDR6,2001:67c:4e8::/48,telegra节点选择,no-resolve #电报
  
  - DOMAIN-KEYWORD,potato,potato节点选择 #电报
  - DOMAIN-KEYWORD,otatop,potato节点选择 #电报
  - DOMAIN-SUFFIX,otatop.app,potato节点选择 #电报

  - DOMAIN-KEYWORD,1drv,微软可直连
  - DOMAIN-KEYWORD,microsoft,微软可直连
  - DOMAIN-SUFFIX,aadrm.com,微软可直连
  - DOMAIN-SUFFIX,acompli.com,微软可直连
  - DOMAIN-SUFFIX,acompli.net,微软可直连
  - DOMAIN-SUFFIX,aka.ms,微软可直连
  - DOMAIN-SUFFIX,akadns.net,微软可直连
  - DOMAIN-SUFFIX,aspnetcdn.com,微软可直连
  - DOMAIN-SUFFIX,assets-yammer.com,微软可直连
  - DOMAIN-SUFFIX,azure.com,微软可直连
  - DOMAIN-SUFFIX,azure.net,微软可直连
  - DOMAIN-SUFFIX,azureedge.net,微软可直连
  - DOMAIN-SUFFIX,azurerms.com,微软可直连
  - DOMAIN-SUFFIX,bing.com,微软可直连
  - DOMAIN-SUFFIX,cloudapp.net,微软可直连
  - DOMAIN-SUFFIX,cloudappsecurity.com,微软可直连
  - DOMAIN-SUFFIX,edgesuite.net,微软可直连
  - DOMAIN-SUFFIX,gfx.ms,微软可直连
  - DOMAIN-SUFFIX,hotmail.com,微软可直连
  - DOMAIN-SUFFIX,live.com,微软可直连
  - DOMAIN-SUFFIX,live.net,微软可直连
  - DOMAIN-SUFFIX,lync.com,微软可直连
  - DOMAIN-SUFFIX,msapp.net,微软可直连
  - DOMAIN-SUFFIX,msauth.net,微软可直连
  - DOMAIN-SUFFIX,msauthimages.net,微软可直连
  - DOMAIN-SUFFIX,msecnd.net,微软可直连
  - DOMAIN-SUFFIX,msedge.net,微软可直连
  - DOMAIN-SUFFIX,msft.net,微软可直连
  - DOMAIN-SUFFIX,msftauth.net,微软可直连
  - DOMAIN-SUFFIX,msftauthimages.net,微软可直连
  - DOMAIN-SUFFIX,msftidentity.com,微软可直连
  - DOMAIN-SUFFIX,msidentity.com,微软可直连
  - DOMAIN-SUFFIX,msn.com,微软可直连
  - DOMAIN-SUFFIX,msocdn.com,微软可直连
  - DOMAIN-SUFFIX,msocsp.com,微软可直连
  - DOMAIN-SUFFIX,mstea.ms,微软可直连
  - DOMAIN-SUFFIX,o365weve.com,微软可直连
  - DOMAIN-SUFFIX,oaspapps.com,微软可直连
  - DOMAIN-SUFFIX,office.com,微软可直连
  - DOMAIN-SUFFIX,office.net,微软可直连
  - DOMAIN-SUFFIX,office365.com,微软可直连
  - DOMAIN-SUFFIX,officeppe.net,微软可直连
  - DOMAIN-SUFFIX,omniroot.com,微软可直连
  - DOMAIN-SUFFIX,onedrive.com,微软可直连
  - DOMAIN-SUFFIX,onenote.com,微软可直连
  - DOMAIN-SUFFIX,onenote.net,微软可直连
  - DOMAIN-SUFFIX,onestore.ms,微软可直连
  - DOMAIN-SUFFIX,outlook.com,微软可直连
  - DOMAIN-SUFFIX,outlookmobile.com,微软可直连
  - DOMAIN-SUFFIX,phonefactor.net,微软可直连
  - DOMAIN-SUFFIX,public-trust.com,微软可直连
  - DOMAIN-SUFFIX,sfbassets.com,微软可直连
  - DOMAIN-SUFFIX,sfx.ms,微软可直连
  - DOMAIN-SUFFIX,sharepoint.com,微软可直连
  - DOMAIN-SUFFIX,sharepointonline.com,微软可直连
  - DOMAIN-SUFFIX,skype.com,微软可直连
  - DOMAIN-SUFFIX,skypeassets.com,微软可直连
  - DOMAIN-SUFFIX,skypeforbusiness.com,微软可直连
  - DOMAIN-SUFFIX,staffhub.ms,微软可直连
  - DOMAIN-SUFFIX,svc.ms,微软可直连
  - DOMAIN-SUFFIX,sway-cdn.com,微软可直连
  - DOMAIN-SUFFIX,sway-extensions.com,微软可直连
  - DOMAIN-SUFFIX,sway.com,微软可直连
  - DOMAIN-SUFFIX,trafficmanager.net,微软可直连
  - DOMAIN-SUFFIX,uservoice.com,微软可直连
  - DOMAIN-SUFFIX,virtualearth.net,微软可直连
  - DOMAIN-SUFFIX,visualstudio.com,微软可直连
  - DOMAIN-SUFFIX,windows-ppe.net,微软可直连
  - DOMAIN-SUFFIX,windows.com,微软可直连
  - DOMAIN-SUFFIX,windows.net,微软可直连
  - DOMAIN-SUFFIX,windowsazure.com,微软可直连
  - DOMAIN-SUFFIX,windowsupdate.com,微软可直连
  - DOMAIN-SUFFIX,wunderlist.com,微软可直连
  - DOMAIN-SUFFIX,yammer.com,微软可直连
  - DOMAIN-SUFFIX,yammerusercontent.com,微软可直连

  - DOMAIN-SUFFIX,aaplimg.com,苹果可直连
  - DOMAIN-SUFFIX,apple.co,苹果可直连
  - DOMAIN-SUFFIX,apple.com,苹果可直连
  - DOMAIN-SUFFIX,apple-cloudkit.com,苹果可直连
  - DOMAIN-SUFFIX,appstore.com,苹果可直连
  - DOMAIN-SUFFIX,cdn-apple.com,苹果可直连
  - DOMAIN-SUFFIX,crashlytics.com,苹果可直连
  - DOMAIN-SUFFIX,icloud.com,苹果可直连
  - DOMAIN-SUFFIX,icloud-content.com,苹果可直连
  - DOMAIN-SUFFIX,me.com,苹果可直连
  - DOMAIN-SUFFIX,mzstatic.com,苹果可直连
  - DOMAIN,www-cdn.icloud.com.akadns.net,苹果可直连

  - DOMAIN-KEYWORD,tiktok,tiktok节点选择

  - DOMAIN-SUFFIX,netflix.com,netflix节点选择
  - DOMAIN-SUFFIX,netflix.net,netflix节点选择
  - DOMAIN-SUFFIX,nflxext.com,netflix节点选择
  - DOMAIN-SUFFIX,nflximg.com,netflix节点选择
  - DOMAIN-SUFFIX,nflximg.net,netflix节点选择
  - DOMAIN-SUFFIX,nflxso.net,netflix节点选择
  - DOMAIN-SUFFIX,nflxvideo.net,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest0.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest1.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest2.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest3.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest4.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest5.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest6.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest7.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest8.com,netflix节点选择
  - DOMAIN-SUFFIX,netflixdnstest9.com,netflix节点选择

  - DOMAIN-SUFFIX,local,全球直连
  - IP-CIDR,127.0.0.0/8,全球直连
  - IP-CIDR,172.16.0.0/12,全球直连
  - IP-CIDR,192.168.0.0/16,全球直连
  - IP-CIDR,10.0.0.0/8,全球直连
  - IP-CIDR,17.0.0.0/8,全球直连
  - IP-CIDR,100.64.0.0/10,全球直连
  - IP-CIDR,106.11.0.0/16,全球直连
  - IP-CIDR,101.227.0.0/16,全球直连
  - IP-CIDR,101.224.0.0/13,全球直连
  - IP-CIDR,119.176.0.0/12,全球直连
  - GEOIP,CN,全球直连

  - MATCH,漏网之鱼

cfw-bypass:
  - qq.com
  - music.163.com
  - '*.music.126.net'
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
#DOMAIN-SUFFIX：域名后缀匹配
#DOMAIN：域名匹配
#DOMAIN-KEYWORD：域名关键字匹配
#IP-CIDR：IP段匹配
#SRC-IP-CIDR：源IP段匹配
#GEOIP：GEOIP数据库（国家代码）匹配
#DST-PORT：目标端口匹配
#SRC-PORT：源端口匹配
#MATCH：全匹配（一般放在最后）
