version: '3.3'
services:
  lanproxy-client:
    image: franklin5/lanproxy-client
    container_name: lanproxy-client
    environment:
     # 这里是在lanproxy后台配置的密钥
     - LANPROXY_KEY=input_your_key
     # 服务器的ip，支持域名
     - LANPROXY_HOST=input_your_host
     
    deploy:
      resources:
        limits:
          #cpus: '0.5'
          memory: 512M
          
    restart: always
