version: '3.3'
services:
  guacd:
    image: dushixiang/guacd:1.3.0
    volumes:
      - ./data:/usr/local/next-terminal/data
    restart:
          always
    
  next-terminal:
    image: dushixiang/next-terminal:v1.3.5
    environment:
      DB: mysql
      # 请修改下面的 MySql 配置，需自行创建数据库和用户
      MYSQL_HOSTNAME: 172.18.0.X
      MYSQL_PORT: 3306
      MYSQL_USERNAME: XXXX
      MYSQL_PASSWORD: XXXX
      MYSQL_DATABASE: XXXX
      # 请修改上面的 MySql 配置，需自行创建数据库和用户
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      
    networks:
     mynetwork:
      ipv4_address: "172.18.0.4"
      
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/usr/local/next-terminal/data
      
    restart:
      always
      
networks:
  default:
    external:
      name: mynetwork
  mynetwork:
    external: true
